# Generated by Django 4.1.7 on 2023-05-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
