# Generated by Django 4.1.7 on 2023-06-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
